/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author Juan Pedro Alvarez-281369
 */
public class MenuArranque extends javax.swing.JFrame {

    /**
     * Creates new form MenuArranque
     */
    public MenuArranque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnSisVacio = new javax.swing.JButton();
        btnSisAnterior = new javax.swing.JButton();
        btnSoloRubros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField1.setText("Seleccione una opcion:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(68, 29, 184, 30);

        btnSisVacio.setText("Sistema Vacio");
        btnSisVacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSisVacioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSisVacio);
        btnSisVacio.setBounds(10, 77, 97, 21);

        btnSisAnterior.setText("Sistema anterior");
        btnSisAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSisAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSisAnterior);
        btnSisAnterior.setBounds(125, 77, 109, 21);

        btnSoloRubros.setText("Solo rubros");
        getContentPane().add(btnSoloRubros);
        btnSoloRubros.setBounds(252, 77, 85, 21);

        setBounds(0, 0, 361, 148);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnSisAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSisAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSisAnteriorActionPerformed

    private void btnSisVacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSisVacioActionPerformed
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnSisVacioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuArranque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuArranque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuArranque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuArranque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuArranque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSisAnterior;
    private javax.swing.JButton btnSisVacio;
    private javax.swing.JButton btnSoloRubros;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
