/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import dominio.Sistema;
import dominio.Capataz;
public class RegistroCapataz extends javax.swing.JFrame {

    private Sistema sis;
    
    public RegistroCapataz(Sistema unSistema) {
        sis = unSistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFldNombre = new javax.swing.JTextField();
        txtFldCedula = new javax.swing.JTextField();
        txtFldDireccion = new javax.swing.JTextField();
        txtFldAnoIngreso = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setText("Cedula:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 90, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setText("Dirección:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 90, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setText("Año de  ingreso a la empresa:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 150, 160, 20);
        getContentPane().add(txtFldNombre);
        txtFldNombre.setBounds(170, 60, 210, 19);
        getContentPane().add(txtFldCedula);
        txtFldCedula.setBounds(170, 90, 210, 19);

        txtFldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtFldDireccion);
        txtFldDireccion.setBounds(170, 120, 210, 19);
        getContentPane().add(txtFldAnoIngreso);
        txtFldAnoIngreso.setBounds(170, 150, 210, 20);

        jButton1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 180, 80, 21);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 60, 70, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Registro Capataz");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 20, 120, 17);

        setBounds(0, 0, 414, 251);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                      
        String nombre = txtFldNombre.getText();
        String cedula = txtFldCedula.getText();
        String direc = txtFldDireccion.getText();
        int anoIngreso = Integer.valueOf(txtFldAnoIngreso.getText());
        Capataz c1 = new Capataz(nombre, cedula, direc, anoIngreso);
        sis.addCapataz(c1); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldDireccionActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFldAnoIngreso;
    private javax.swing.JTextField txtFldCedula;
    private javax.swing.JTextField txtFldDireccion;
    private javax.swing.JTextField txtFldNombre;
    // End of variables declaration//GEN-END:variables
}
